# Options for analysis running.
run:
  concurrency: 4
  timeout: 5m
  tests: true
  modules-download-mode: readonly
  allow-parallel-runners: false

# output configuration options
output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters:
  disable-all: true
  enable:
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - copyloopvar
    - cyclop
    - durationcheck
    - err113
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - forbidigo
    - forcetypeassert
    - gocognit
    - goconst
    - gocritic
    - gofmt
    - gomoddirectives
    - gosec
    - gosimple
    - govet
    - grouper
    - ineffassign
    - makezero
    - misspell
    - mnd
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nosprintfhostport
    - paralleltest
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - testpackage
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - varnamelen
    - wrapcheck
    - wsl

issues:
  new: false
  fix: false
  new-from-rev: b5fdfaa2bd30e666511e4648f27d8a26fd8512cb
  uniq-by-line: true
  exclude-rules:
    - path: _test\.go
      linters:
        - containedctx
        - err113
        - forcetypeassert
        - goconst
        - varnamelen
        - wrapcheck

linters-settings:
  mnd:
    ignored-functions:
      - context.WithTimeout
  nolintlint:
    require-specific: true
    require-explanation: true
  revive:
    rules:
      - name: var-naming
        disabled: true
  varnamelen:
    max-distance: 10
    ignore-type-assert-ok: true
    ignore-map-index-ok: true
    ignore-chan-recv-ok: true
    ignore-names:
      - err
      - id
    ignore-decls:
      - i int
